## Stage names in the pipeline.
stages:
  - build
  - deploy

variables:
  ## Name for the generated image. Change this if you wish, but watch out
  ## for special characters and spaces!
  DOCKER_IMAGE_NAME: ${DOCKER_REGISTRY}/tjts5901
  DOCKER_TAG: latest

  ## (Optional) More verbose output from pipeline. Enabling it might reveal secrets.
  #CI_DEBUG_TRACE: "true"


## Use buildkit to build the container. `docker build` requires elevated
## privileges, and can be security issue: https://docs.gitlab.com/runner/executors/kubernetes.html#using-dockerdind
## Buildkit: https://github.com/moby/buildkit
## Example gitlab-ci buildkit template: https://gitlab.com/txlab/ci-templates
build:
  stage: build
  image:
    name: moby/buildkit:rootless
    entrypoint: [ "sh", "-c" ]
  variables:
    BUILDKITD_FLAGS: --oci-worker-no-process-sandbox

  before_script:
    ## Make some checks that Docker credentials are configured.
    - test -z "${DOCKER_REGISTRY}" && (echo "Missing required variable DOCKER_REGISTRY. See 'Pipeline setup.md'"; exit 1)
    - test -z "${DOCKER_AUTH_CONFIG}" && (echo "Missing required variable DOCKER_AUTH_CONFIG. See 'Pipeline setup.md'"; exit 1)
    - test -z "${DOCKER_IMAGE_NAME}" && (echo "Missing image name variable."; exit 1)
    ## Simple check that the registry exists in login information
    - grep "\\b${DOCKER_REGISTRY}\\b" "${DOCKER_AUTH_CONFIG}" || (echo "Could not find docker registry in docker login information. Check DOCKER_AUTH_CONFIG"; exit 1)
    ## Copy docker login credentials from gitlab into a place where buildkit is looking for them.
    - mkdir -p ${HOME}/.docker && cp "${DOCKER_AUTH_CONFIG}" "${HOME}/.docker/config.json"

  script:
    # Build the image, and push it to registry.
    - |
      buildctl-daemonless.sh build  --progress=plain \
          --frontend=dockerfile.v0 \
          --local context=. \
          --local dockerfile=. \
          --opt build-arg:CI_COMMIT_SHA=${CI_COMMIT_SHA} \
          --output type=image,name=${DOCKER_IMAGE_NAME}:${DOCKER_TAG},push=true
