## Course Documentation
## ====================
##
## If you wish to build documentation, run:
##  $ pip install mkdocs mkdocs-material
##  $ mkdocs build -f docs/mkdocs.yml

site_name: JYU TJTS5901 Course Documentation
theme: 
  name: material
  features:
    - navigation.sections
    - content.code.copy
    - toc.follow
  font:
    text: lato
  logo: https://gitlab.jyu.fi/uploads/-/system/appearance/header_logo/1/jyu-logo3.png

repo_url: https://gitlab.jyu.fi/startuplab/courses/tjts5901-continuous-software-engineering/TJTS5901-K23_template
repo_name: tjts5901-continuous-software-engineering/TJTS5901-K23_template
#edit_uri: -/edit/main/
docs_dir: tjts5901
site_dir: ../_docs

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  social:
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.jyu.fi/startuplab/courses/tjts5901-continuous-software-engineering/TJTS5901-K23_template
    - icon: fontawesome/solid/graduation-cap
      link: https://moodle.jyu.fi/course/view.php?id=20888
    - icon: fontawesome/solid/fire
      link: https://sisu.jyu.fi/student/courseunit/otm-38b7f26b-1cf9-4d2d-a29b-e1dcb5c87f00

plugins:
  - offline